spring.application.name=conta-bancaria-api

# Datasource (dev - use docker-compose postgres)
spring.datasource.url=jdbc:postgresql://localhost:5432/bankdb
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.generate-ddl-auto=true

# Audit
spring.jpa.properties.org.hibernate.envers.default_schema=audit
spring.jpa.properties.org.hibernate.envers.audit_table_suffix=_audit

# Actuator
management.endpoints.web.exposure.include=health,info

